services:
  user:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: 'npm run start:dev user'
    # ports:
    #   - 3000:3000

  product:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: 'npm run start:dev product'
    # ports:
    #   - 3001:3000

  payment:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: 'npm run start:dev payment'

  shipping:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: 'npm run start:dev shipping'

  media:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: 'npm run start:dev media'

  order:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: 'npm run start:dev order'

  stock:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: 'npm run start:dev stock'

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - user
      - product
      - payment
      - shipping
      - media
      - order
      - stock
